# Generated by Django 4.2.20 on 2025-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganizationalUnit', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLStagiaire',
            fields=[
                ('cluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.cluser')),
                ('etablissement', models.CharField(blank=True, help_text="Nom de l'établissement", max_length=100, null=True)),
                ('theme', models.CharField(blank=True, help_text='Thème du stage', max_length=200, null=True)),
                ('filiere', models.CharField(blank=True, help_text='Filière du stagiaire', max_length=100, null=True)),
                ('option', models.CharField(blank=True, help_text='Option du stagiaire', max_length=100, null=True)),
                ('organisationUnit', models.ForeignKey(blank=True, help_text='Unité organisationnelle du stagiaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='OrganizationalUnit.organizationalunit')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable du stagiaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='users.cluser')),
            ],
            bases=('users.cluser',),
        ),
    ]
