# Generated by Django 4.2.20 on 2025-05-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clstagiaire',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='clstagiaire',
            name='date_fin',
        ),
    ]
