# Generated by Django 4.2.20 on 2025-05-26 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnm', models.CharField(max_length=50)),
                ('tpm', models.CharField(blank=True, max_length=50, null=True)),
                ('tsx', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')], default='Masculin', max_length=10)),
                ('dns', models.DateField()),
                ('date_retraite', models.DateField(blank=True, null=True)),
                ('tlns', models.CharField(blank=True, max_length=50, null=True)),
                ('tads', models.CharField(blank=True, max_length=50, null=True)),
                ('teml', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('tphne', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ttvst', models.CharField(blank=True, max_length=50, null=True)),
                ('dsb', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ddf', models.DateField(blank=True, null=True)),
                ('matricule', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('echelon', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
                ('observation', models.TextField(blank=True, null=True)),
                ('tstt_user', models.CharField(blank=True, choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('tstt', models.CharField(blank=True, max_length=50, null=True)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialite.specialite')),
            ],
        ),
    ]
