# Generated by Django 4.2.20 on 2025-04-17 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluser',
            name='echelon',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='cluser',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cluser',
            name='matricule',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluser',
            name='ttvst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
