# Generated by Django 4.2.20 on 2025-04-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialite', '0003_alter_specialite_designation'),
        ('users', '0002_cluser_echelon_cluser_grade_cluser_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluser',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialite.specialite'),
        ),
    ]
