# Generated by Django 4.2.20 on 2025-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cluser_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluser',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluser',
            name='tstt_user',
            field=models.CharField(blank=True, choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=50, null=True),
        ),
    ]
