# Generated by Django 4.2.20 on 2025-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cluser_observation_cluser_tstt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluser',
            name='matricule',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
