# Generated by Django 4.2.20 on 2025-04-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('specialite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLEmploye',
            fields=[
                ('cluser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.cluser')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='specialite.specialite')),
            ],
            bases=('users.cluser',),
        ),
    ]
