# Generated by Django 4.2.20 on 2025-04-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clemploye',
            name='specialite',
        ),
    ]
