# Generated by Django 4.2.20 on 2025-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganizationalUnit', '0001_initial'),
        ('Stagiaire', '0001_initial'),
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLParcoursStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, help_text='Entrez les compétences séparées par des virgules', null=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganizationalUnit.organizationalunit')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours_responsable', to='Employe.clemploye')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stagiaire.clstagiaire')),
            ],
        ),
    ]
