# Generated by Django 4.2.20 on 2025-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStagiaaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clparcoursstagiaire',
            name='competence',
        ),
        migrations.AddField(
            model_name='clparcoursstagiaire',
            name='competences',
            field=models.CharField(blank=True, help_text='Compétences sous forme de texte, séparées par des virgules', max_length=1024, null=True),
        ),
    ]
