# Generated by Django 4.2.20 on 2025-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcoursStagiaaire', '0002_remove_clparcoursstagiaire_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clparcoursstagiaire',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clparcoursstagiaire',
            name='competences',
            field=models.TextField(blank=True, help_text='Entrez les compétences séparées par des virgules', null=True),
        ),
        migrations.AlterField(
            model_name='clparcoursstagiaire',
            name='evaluation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
