# Generated by Django 4.2.20 on 2025-04-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme_affecte', models.CharField(max_length=50)),
                ('lieu_affectation', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Définitif', 'Définitif')], max_length=10)),
                ('motif_affectation', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='Employe.clemploye')),
            ],
        ),
    ]
