# Generated by Django 4.2.20 on 2025-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'unité (ex. 'II-1-1 Sections Français')", max_length=50, unique=True)),
                ('designation', models.TextField(blank=True, help_text="Désignation ou description de l'unité", null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Unité parente dans la hiérarchie (laisser vide pour une unité de premier niveau)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='OrganizationalUnit.organizationalunit')),
                ('unite', models.ForeignKey(help_text='Unité de rattachement (par exemple, une unité fonctionnelle globale)', on_delete=django.db.models.deletion.CASCADE, related_name='organizational_units', to='unite.unite')),
            ],
            options={
                'verbose_name': 'Unité Organisationnelle',
                'verbose_name_plural': 'Unités Organisationnelles',
                'ordering': ['name'],
            },
        ),
    ]
