# Generated by Django 4.2.20 on 2025-04-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unite', '0002_unite_unite_parent'),
        ('OrganizationalUnit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='designation',
            field=models.TextField(blank=True, help_text="Désignation ou description de l'unité", null=True),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Unité parente dans la hiérarchie (laisser vide pour une unité de premier niveau)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='OrganizationalUnit.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='unite',
            field=models.ForeignKey(help_text='Unité de rattachement (par exemple, une unité fonctionnelle globale)', on_delete=django.db.models.deletion.CASCADE, related_name='organizational_units', to='unite.unite'),
        ),
    ]
