# Generated by Django 4.2.20 on 2025-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu_mission', models.CharField(max_length=50)),
                ('organisme', models.CharField(max_length=50)),
                ('conclusion_mission', models.TextField(blank=True, null=True)),
                ('employe_signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employe.clemploye')),
            ],
        ),
    ]
